openapi: 3.0.1
components:
  schemas:
    DistributionInput:
      type: object
      required:
      properties:
        ID:
          type: number
        share:
          type: string
      example:
        distribution:
          - ID: 1
            share: "25.000000000000"
          - ID: 2
            share: "75.000000000000"
