version: "3.9"
services:
  database:
    build: "./db"
    ports:
      - "3306:3306"
    restart: always
    command: --log-bin-trust-function-creators=1
    environment:
      MYSQL_DATABASE: "EffektDonasjonDB_Local"
      MYSQL_ROOT_PASSWORD: "effekt"
      MYSQL_USER: "api"
      MYSQL_PASSWORD: "effekt"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysql $${MYSQL_DATABASE} -h localhost --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --silent --execute "SELECT * FROM $${MYSQL_DATABASE}.Seeded" 2>/dev/null | grep -w Completed
      interval: 1s
      timeout: 1s
      retries: 120
  api:
    build: .
    ports:
      - "5050:5050"
    depends_on:
      database:
        condition: service_healthy
    environment:
      PORT: 5050
      HOST: 0.0.0.0
      DB_HOST: database
      DB_NAME: "EffektDonasjonDB_Local"
      DB_USER: "api"
      DB_PASS: "effekt"
      DATABASE_URL: "mysql://api:effekt@database:3306/EffektDonasjonDB_Local"
      DBMATE_MIGRATIONS_DIR: "/home/node/app/db/migrations"
    volumes:
      - ./:/home/node/app/
    links:
      - database
