version: "3"

volumes:
  effekt-mysql_volume:

services:
  db:
    image: mysql:latest
    container_name: effekt-mysql
    ports:
      - 3306:3306
    command: ["--log_bin_trust_function_creators=1"]
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    env_file:
      - .env
    volumes:
      - effekt-mysql_volume:/var/lib/mysql
    restart: unless-stopped
