/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    /** @example [object Object] */
    ApiResponse: {
      /** @description The http status of the request */
      status?: number;
      /** @description Some object depending on the route */
      content?: unknown;
    };
  };
}

export interface operations {}

export interface external {}
