/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    /** @example [object Object] */
    Donor: {
      /** @description The Auto-generated id of a donor */
      id?: number;
      /** @description Donors email (unique identifier) */
      email: string;
      /** @description Full name of the donor (first and last name) */
      name: string;
      /** @description The social security number of the donor */
      ssn?: number;
      /** @description Set to true if donor wishes to subscribe to newsletter */
      newsletter?: boolean;
      /** @description Set to true if spam / test donor */
      trash?: boolean;
      /**
       * Format: date-time
       * @description The date and time the donor was registered
       */
      registered?: string;
    };
  };
}

export interface operations {}

export interface external {}
