/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    /**
     * @example {
     *   "ID": 1,
     *   "organization": "Against Malaria Foundation",
     *   "abbriv": "AMF",
     *   "value": "18.000000000000000000",
     *   "year": 2018
     * }
     */
    AggregatedDonation: {
      /** @description The organization's ID */
      ID?: number;
      /** @description The name of the organization */
      organization?: string;
      /** @description Abbreviation of the organization's name */
      abbriv?: string;
      /** @description The amount that was donated */
      value?: string;
      /** @description The year the donation was made */
      year?: number;
    };
  };
}

export interface operations {}

export interface external {}
