/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @example {
     *   "ID": 1,
     *   "organization": "Against Malaria Foundation",
     *   "abbriv": "AMF",
     *   "value": "18.000000000000000000",
     *   "year": 2018
     * }
     */
    AggregatedDonation: {
      /** @description The organization's ID */
      ID?: number;
      /** @description The name of the organization */
      organization?: string;
      /** @description Abbreviation of the organization's name */
      abbriv?: string;
      /** @description The amount that was donated */
      value?: string;
      /** @description The year the donation was made */
      year?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
