/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    /**
     * @example {
     *   "KID": "51615227",
     *   "sum": "250.00",
     *   "count": 1,
     *   "full_name": "Jack Torance",
     *   "email": "jack@overlookhotel.com"
     * }
     */
    AggregatedDistribution: {
      /** @description The customer identification number */
      KID?: string;
      /** @description The sum of all the donations for the given distribution in decimal form */
      sum?: string;
      /** @description The number of donations for the given distribution */
      count?: number;
      /** @description Full name of the donor (first and last name) */
      full_name?: string;
      /** @description The email of the donor */
      email?: string;
    };
  };
}

export interface operations {}

export interface external {}
