/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** Type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type OneOf<T extends any[]> = T extends [infer Only] ? Only : T extends [infer A, infer B, ...infer Rest] ? OneOf<[XOR<A, B>, ...Rest]> : never;

export type paths = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @example {
     *   "KID": "51615227",
     *   "sum": "250.00",
     *   "count": 1,
     *   "full_name": "Jack Torance",
     *   "email": "jack@overlookhotel.com"
     * }
     */
    AggregatedDistribution: {
      /** @description The customer identification number */
      KID?: string;
      /** @description The sum of all the donations for the given distribution in decimal form */
      sum?: string;
      /** @description The number of donations for the given distribution */
      count?: number;
      /** @description Full name of the donor (first and last name) */
      full_name?: string;
      /** @description The email of the donor */
      email?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
