/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    /**
     * @example {
     *   "id": 3,
     *   "active": 0,
     *   "amount": 7,
     *   "KID": 59488197,
     *   "payment_date": 15,
     *   "created": "2022-02-04T18:28:21.000Z",
     *   "last_updated": "2022-02-04T18:28:21.000Z",
     *   "notice": 1,
     *   "full_name": "Keno Johnsen"
     * }
     */
    AvtalegiroAgreement: {
      /** @description The Auto-generated id of a agreement */
      id: number;
      /** @description If the avtale agreement is active or not */
      active: boolean;
      /** @description Amount for the payment agreement */
      amount: number;
      /** @description The KID number for the agreement */
      KID: string;
      /**
       * Format: date-time
       * @description The date for payment
       */
      payment_date: string;
      /**
       * Format: date-time
       * @description Timestamp for when the agreement were created
       */
      created: string;
      /**
       * Format: date-time
       * @description Timestamp for when the agreement were last updated
       */
      last_updated: string;
      /** @description If you recieve notification or not */
      notice: boolean;
      /** @description The full name of the donor */
      full_name: string;
    };
  };
}

export interface operations {}

export interface external {}
