/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @example {
     *   "id": 1,
     *   "name": "Global Health",
     *   "shortDescription": "This cause area is about global health",
     *   "longDescription": "This is a longer description about global health",
     *   "informationUrl": "https://gieffektivt.no/cause-areas/global-health/",
     *   "isActive": true,
     *   "ordering": 1
     * }
     */
    CauseArea: {
      /** @description The cause area id */
      id: number;
      /** @description The cause area name */
      name: string;
      /** @description The cause area standard percentage share */
      standardPercentageShare?: number;
      /** @description The cause area short description */
      shortDescription: string;
      /** @description The cause area long description */
      longDescription: string;
      /** @description The cause area information url */
      informationUrl: string;
      /** @description Whether the cause area is active */
      isActive: boolean;
      /** @description The cause area ordering */
      ordering: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
