/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    /**
     * @example {
     *   "distribution": [
     *     {
     *       "ID": 1,
     *       "share": "25.000000000000"
     *     },
     *     {
     *       "ID": 2,
     *       "share": "75.000000000000"
     *     }
     *   ]
     * }
     */
    DistributionInput: {
      ID?: number;
      share?: string;
    };
  };
}

export interface operations {}

export interface external {}
