/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    /**
     * @example {
     *   "id": 5,
     *   "name": "Against Malaria Foundation",
     *   "share": "25.00"
     * }
     */
    DistributionOrganization: {
      /** @description The organization id */
      id?: number;
      /** @description The organization name */
      name?: string;
      /** @description The percentage share for the given organizations in decimal form */
      share?: string;
    };
  };
}

export interface operations {}

export interface external {}
