/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    /**
     * @example {
     *   "KID": "000013901401",
     *   "organizations": [
     *     {
     *       "id": 5,
     *       "name": "Against Malaria Foundation",
     *       "share": "25.00"
     *     },
     *     {
     *       "id": 6,
     *       "name": "GiveWells tildelingsfond",
     *       "share": "75.00"
     *     }
     *   ]
     * }
     */
    Distribution: {
      /** @description The KID of the distribution */
      KID?: string;
      organizations?: any;
    };
  };
}

export interface operations {}

export interface external {}
