/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    /**
     * @example {
     *   "id": 237,
     *   "label": "OCR",
     *   "timestamp": "2018-03-29T23:00:00.000Z",
     *   "meta": "Donations [ Added: 17 Invalid: 0 ] Agreements [ Activated: 1 Terminated: 0 ]"
     * }
     */
    LogEntry: {
      /** @description The Auto-generated id of an entry */
      id?: number;
      /** @description The type of log entry (e.g. OCR import, Avtlaegiro claims, Vipps recurring donations sync) */
      label?: string;
      /**
       * Format: date-time
       * @description The date and time the log entry vas added
       */
      timestamp?: string;
      /** @description An optional short summary for the log entry */
      meta?: string;
    } & {
      email: unknown;
      name: unknown;
    };
  };
}

export interface operations {}

export interface external {}
