/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    /**
     * @example {
     *   "pages": 100
     * }
     */
    Pagination: {
      /** @description The number of pages for the given limit. E.g. if the client has a limit of 20 results, and there are 2000 items in the database, there would be 100 pages. */
      pages?: number;
      /** @description An array of objects depending on the route / resource */
      rows?: unknown[];
    };
  };
}

export interface operations {}

export interface external {}
