/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    /**
     * @example {
     *   "id": 1234,
     *   "typeId": 10,
     *   "donorId": 3,
     *   "answer": "Moralfilosofisk tankeeksperiment",
     *   "timestamp": "2021-12-28T10:13:24.000Z",
     *   "session": "1657788222552",
     *   "active": "boolean;"
     * }
     */
    ReferralAnswer: {
      /** @description The auto-generated id of a referral answer */
      id: number;
      /** @description The auto-generated id of a referral type */
      typeId: number;
      /** @description The auto-generated id of the Donor */
      donorId: number;
      /** @description The referral answer */
      answer: string;
      /**
       * Format: date-time
       * @description When the referral answer was registered
       */
      timestamp?: string;
      /** @description The web session */
      session?: string;
      /** @description Whether or not this referral type is currently enabled */
      active: boolean;
    };
  };
}

export interface operations {}

export interface external {}
