/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    /**
     * @example {
     *   "year": 2019,
     *   "units": [
     *     {
     *       "id": 984,
     *       "name": "Overlook Hotel Logistics Ltd.",
     *       "ssn": 919809140,
     *       "sumDonations": 100000,
     *       "taxDeduction": 25000,
     *       "channel": "Gi Effektivt"
     *     }
     *   ],
     *   "sumTaxDeductionsByChannel": [
     *     {
     *       "channel": "Gi Effektivt",
     *       "sumTaxDeductions": 25000
     *     }
     *   ],
     *   "sumTaxDeductions": 25000
     * }
     */
    TaxReport: {
      /** @description The year the report is for */
      year?: number;
      /** @description The tax units for the year */
      units?: components["schemas"]["TaxYearlyReportUnit"][];
      /** @description The sum of all tax deductions for the year and channel */
      sumTaxDeductionsByChannel?: {
        /** @description The channel (or entity the donations where given to) for the tax unit for the year and channel */
        channel?: string;
        /** @description The sum of all donations for the tax unit for the year and channel */
        sumTaxDeductions?: number;
      }[];
      /** @description The sum of all tax deductions for the year */
      sumTaxDeductions?: number;
    };
    /**
     * @example {
     *   "id": 984,
     *   "name": "Overlook Hotel Logistics Ltd.",
     *   "ssn": 919809140,
     *   "sumDonations": 100000,
     *   "taxDeduction": 25000,
     *   "channel": "Gi Effektivt"
     * }
     */
    TaxYearlyReportUnit: {
      /** @description The Auto-generated id for a tax unit */
      id?: number;
      /** @description Full name of the tax unit (either a personal name or a business entity) */
      name?: string;
      /** @description Either a personal number or the number for the business entity */
      ssn?: string;
      /** @description The sum of all donations for the tax unit for the year and channel */
      sumDonations?: number;
      /** @description The tax deduction for the tax unit for the year and channel */
      taxDeduction?: number;
      /** @description The channel (or entity the donations where given to) for the tax unit for the year and channel */
      channel?: string;
    };
  };
}

export interface operations {}

export interface external {}
