/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    /**
     * @example {
     *   "id": 984,
     *   "donorId": 237,
     *   "name": "Overlook Hotel Logistics Ltd.",
     *   "ssn": 919809140,
     *   "registered": "1921-07-04T23:00:00.000Z"
     * }
     */
    TaxUnit: {
      /** @description The Auto-generated id for a tax unit */
      id: number;
      /** @description The id of the donor assicoated with the tax unit */
      donorId: number;
      /** @description Full name of the tax unit (either a personal name or a business entity) */
      name: string;
      /** @description The social security number of the tax unit */
      ssn?: string;
    };
  };
}

export interface operations {}

export interface external {}
